### PR TITLE
Use Eigen::AngleAxisd for exponential maps

### PR DESCRIPTION
**Pull request by mxgrey**
A simple fix to FreeJoint::convertToTransform(~) plus a regression test.

### CODE REVIEW

**Comment by mxgrey** [comment]
The latest change addressed the second part of #333. It seems that DART's built-in logMap function is not robust to imprecision in the rotation matrices that it's given. In the example given in the bug report, the built-in logMap function decided to reflect the rotation that was fed to it.

So instead, I've changed the logMap function to use Eigen::AngleAxisd which is very robust (and which solved the issue brought up in #333). In response to #88 I ran a speedtest to compare DART's built-in implementation to the speed of Eigen::AngleAxisd. Interestingly, the Eigen version was consistently faster. The dynamics speed test had, on average, a 15% reduction in time and the kinematics test had, on average, a 4% reduction in time using Eigen::AngleAxisd.

It seems that Eigen::AngleAxisd is faster and more robust than the existing DART implementation, so it would be a good idea to adopt it with this pull request.

**Comment by jslee02** [comment]
Can you split this into two separate pull requests: Fix FreeJoint::convertToTransform() and Eigen::AngleAxis?

Fix FreeJoint::converToTransform() looks fine, but I'd like to do more tests on Eigen::AngleAxis such as the angle range, the robustness near zero angle.

**Comment by mxgrey** [comment]
The first commit from this pull request is now available in #338 as its own pull request.

**Comment by jslee02** [comment]
I think I messed up this PR and it's too old where the changes are small. Could you recreate clean PR?

**Pull request closed without merging**
