### PR TITLE
Fix memory alignment in loading meshes

### PR DESCRIPTION
**Pull request by jslee02**
This pull request addresses the memory alignment issue with Eigen object in loading meshes, which was reported by @jturner65 in #599.

### CODE REVIEW

**Comment by mxgrey** [comment]
The changes look good :+1:, but is there a particular reason that VS can't compile it in release mode? Is it just timing out?

**Comment by jslee02** [comment]
Hm, I'm not sure. Let me make AppVeyor test it again, and test it myself on my virtual machine in parallel to figure it out.

**Comment by jslee02** [comment]
I got an error as:
```
c:\golems\include\eigen\src\core\assign.h(527): fatal error C1002: compiler is out of heap space in pass 2
```

It seems it needs too much heap memory for 32 bit Windows to build DART. One possible solution would be optimizing the header inclusion as the suggestion of the first answer in [this post](http://stackoverflow.com/questions/1388608/how-to-work-around-visual-studio-compiler-crashes).

**Comment by mxgrey** [comment]
It's very likely that our header organization could be improved dramatically, although I'm afraid it might require some refactoring of classes, such as decomposing them into simpler classes and carefully sorting through the dependencies between them.

I don't know who would have time to actually do that, or when.

**Comment by jslee02** [comment]
Yeah, we should give it a try to improve the header organization at some point, but not now. I'm merging this PR, and creating a new issue for this build failure that might be related to the header organization.

**Pull request merged**
