### PR TITLE
Add Python bindings for CollisionFilter

### PR DESCRIPTION
**Pull request by jslee02**
This PR is created based on #1457.

***

**Before creating a pull request**

- [x] Document new methods and classes
- [x] Format new code files using `clang-format`

**Before merging a pull request**

- [x] Set version target by selecting a milestone on the right side
- [x] Summarize this change in `CHANGELOG.md`
- [x] Add unit test(s) for this change

### CODE REVIEW

**Comment by costashatz** [comment]
@jslee02 this PR causes python bindings on my system (Xubuntu 18.04) to fail with segfault everytime I do `import dartpy` (I will try later today on my archlinux system to check if it makes it break there also). Any ideas what could be causing this? Is it passing the tests (I assume you have tests for executing python examples)?

**Comment by jslee02** [comment]
Did it work on your system before this PR?

> Is it passing the tests (I assume you have tests for executing python examples)?

Yes: https://github.com/dartsim/dart/runs/665747409#step:4:583

**Comment by costashatz** [comment]
> Did it work on your system before this PR?

Yes and I tried again going back to a previous commit and it is working again.

> Yes: https://github.com/dartsim/dart/runs/665747409#step:4:583

I am using Ubuntu 18.04, but they still pass in your CIs.

Any ideas on what I can check? I could do a debug build and see if I can find something in the trace but I doubt it.

**Comment by costashatz** [comment]
@jslee02 in arch-linux I am getting the following when doing `import dartpy`:

```
ImportError: /usr/lib/python3.8/site-packages/dartpy.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN4dart6python15CollisionFilterERN8pybind116moduleE
```

Again, if I revert to a previous commit, it is working.

**Comment by costashatz** [comment]
@jslee02 after cleaning up the cmake build folder and re-configuring, it seems that it is working. So, I guess it was a CMake thing.. Sorry for the fuzz..

**Comment by jslee02** [comment]
Glad it worked!

**Pull request merged**
