### PR TITLE
Changing header extension from .h to .hpp

### PR DESCRIPTION
**Pull request by jslee02**
This PR changes head extension from `.h` to `.hpp` as proposed in #568.

Exceptions: ode files and lodepng.h

This pull request includes #652. See [this](https://github.com/dartsim/dart/compare/packaging/components...packaging/h_to_hpp) to see only the changes made after #652.

### CODE REVIEW

**Comment by mxgrey** [comment]
In a day or two I'll have a pull request coming in related to #643 where we end up with some new files and remove some old ones. That'll be guaranteed to have merge conflicts with this.

I suggest we hold off on renaming files and renaming "DART" instances until we've 100% finalized DART 6.0. Otherwise we'll probably end up with ugly merge conflicts and needing to duplicate efforts.

Also, I'm not sure if we should rename the file extensions in DART 6.0. I was thinking we might just want to rename the extensions for KIDO to simplify the API incompatibility between DART 5 and DART 6.

**Comment by jslee02** [comment]
> I suggest we hold off on renaming files and renaming "DART" instances until we've 100% finalized DART 6.0. Otherwise we'll probably end up with ugly merge conflicts and needing to duplicate efforts.

Right, I'll try to resolve the merge conflict once your PR for #643 is merged (or created) since I already put some efforts already. :sweat: 

Another concern I have is the confliction between #631 and `grey/aspects`. Do you see #631 can be merged to your branch without ugly merge conflicts? 

> Also, I'm not sure if we should rename the file extensions in DART 6.0. I was thinking we might just want to rename the extensions for KIDO to simplify the API incompatibility between DART 5 and DART 6.

I thought we intend to minimizing the difference in transitioning from DART 6.0 to KIDO 7.0 (just name change). I'm a bit inclined to making this change in DART 6.0 because the incompatibility of file extension can be straightforwardly resolved by including `dart.hpp` and a few additional component headers like `dart/utils/utils.hpp`.

**Comment by mxgrey** [comment]
> I'm a bit inclined to making this change in DART 6.0 because the incompatibility of file extension can be straightforwardly resolved by including dart.hpp and a few additional component headers like dart/utils/utils.hpp.

That's a fair point. An alternative might be to "deprecate" the ``.h`` extension by having ``.h`` files that simply ``#include`` the ``.hpp`` files, but that might make the source tree too messy.

I suppose I'm okay with it either way. No matter what, it'll be like ripping off band-aid; it's painful but needs to be done sooner or later.

> Another concern I have is the confliction between #631 and grey/aspects. Do you see #631 can be merged to your branch without ugly merge conflicts?

It won't be a trivial merge, but I don't believe it will be very painful either. Any merge conflicts there will be the renaming of ``*Addon*`` to ``*Aspect*``, which is pretty easy to resolve with a search-and-replace.

**Comment by jslee02** [comment]
Will recreate another clean PR once the current open pull request are all merged. Closing.

**Pull request closed without merging**
