### PR TITLE
Fix path to glut.h for macOS

### PR DESCRIPTION
**Pull request by jslee02**
This PR fixes the path to `glut.h` thanks to @ilovezfs (see this [comment](https://github.com/Homebrew/homebrew-core/pull/29620#issuecomment-405043890)).

Additionally, this PR fixes linking to glut. According to the [CMake doc](https://cmake.org/cmake/help/latest/module/FindGLUT.html), it seems we should generally use `GLUT_LIBRARIES` rather than `GLUT_glut_LIBRARY`.

***

**Before merging a pull request**

- [x] Set version target by selecting a milestone on the right side

### CODE REVIEW

**Comment by ilovezfs** [comment]
hmm is this correct? `<GLUT/glut.h>` is the path for freeglut headers, which I thought you're dropping.

**Comment by ilovezfs** [comment]
Interestingly, it seems to end up using X11's
```
iMac-TMP:~ joe$ brew linkage dartsim
System libraries:
  /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
  /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
  /opt/X11/lib/libglut.3.dylib
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
Homebrew libraries:
  /usr/local/opt/assimp/lib/libassimp.4.dylib (assimp)
  /usr/local/opt/boost/lib/libboost_filesystem-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_regex-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_system-mt.dylib (boost)
  /usr/local/opt/bullet/lib/libBulletCollision.2.87.dylib (bullet)
  /usr/local/opt/bullet/lib/libBulletDynamics.2.87.dylib (bullet)
  /usr/local/opt/bullet/lib/libBulletSoftBody.2.87.dylib (bullet)
  /usr/local/opt/bullet/lib/libLinearMath.2.87.dylib (bullet)
  /usr/local/opt/console_bridge/lib/libconsole_bridge.0.4.dylib (console_bridge)
  /usr/local/opt/fcl/lib/libfcl.7.dylib (fcl)
  /usr/local/opt/flann/lib/libflann_cpp.1.9.dylib (flann)
  /usr/local/opt/libccd/lib/libccd.2.dylib (libccd)
  /usr/local/opt/nlopt/lib/libnlopt_cxx.0.dylib (nlopt)
  /usr/local/opt/octomap/lib/liboctomap.1.9.dylib (octomap)
  /usr/local/opt/octomap/lib/liboctomath.1.9.dylib (octomap)
  /usr/local/opt/open-scene-graph/lib/libOpenThreads.21.dylib (open-scene-graph)
  /usr/local/opt/open-scene-graph/lib/libosg.157.dylib (open-scene-graph)
  /usr/local/opt/open-scene-graph/lib/libosgDB.157.dylib (open-scene-graph)
  /usr/local/opt/open-scene-graph/lib/libosgGA.157.dylib (open-scene-graph)
  /usr/local/opt/open-scene-graph/lib/libosgManipulator.157.dylib (open-scene-graph)
  /usr/local/opt/open-scene-graph/lib/libosgShadow.157.dylib (open-scene-graph)
  /usr/local/opt/open-scene-graph/lib/libosgViewer.157.dylib (open-scene-graph)
  /usr/local/opt/tinyxml2/lib/libtinyxml2.6.dylib (tinyxml2)
  /usr/local/opt/urdfdom/lib/liburdfdom_model.1.0.dylib (urdfdom)
  /usr/local/opt/urdfdom/lib/liburdfdom_model_state.1.0.dylib (urdfdom)
  /usr/local/opt/urdfdom/lib/liburdfdom_sensor.1.0.dylib (urdfdom)
  /usr/local/opt/urdfdom/lib/liburdfdom_world.1.0.dylib (urdfdom)
Indirect dependencies with linkage:
  console_bridge
  octomap
Variable-referenced libraries:
  @rpath/libdart-external-imgui.6.6.dylib
  @rpath/libdart-external-lodepng.6.6.dylib
  @rpath/libdart-external-odelcpsolver.6.6.dylib
  @rpath/libdart-gui.6.6.dylib
  @rpath/libdart-utils.6.6.dylib
  @rpath/libdart.6.6.dylib
Dependencies with no linkage:
  eigen
iMac-TMP:~ joe$ 
```
:(

**Comment by jslee02** [comment]
Yeah, I could build `dartsim` without installing `freeglut` so I assumed it links to the system glut. :thinking:

**Comment by ilovezfs** [comment]
If I
```
brew cask zap --force xquartz
```
then it links to system GLUT. I wonder how it's finding the header.

**Comment by ilovezfs** [comment]
I guess GLUT/glut.h works because that's the framework name even though there is no GLUT directory.

**Comment by ilovezfs** [comment]
Regarding the X11 thing, see also

https://gitlab.kitware.com/cmake/cmake/issues/16045
https://cmake.org/Bug/view.php?id=16045

So we'll probably need to pass
```
-DGLUT_glut_LIBRARY=/System/Library/Frameworks/GLUT.framework
```
in the formula since X11 is installed on CI.

**Comment by ilovezfs** [comment]
Yup, I just checked the bottle produced by https://github.com/Homebrew/homebrew-core/pull/30092 and it's linked to X11.

**Comment by jslee02** [comment]
The description of the issue makes sense to me. Let me update the dartsim PR in homebrew-core accordingly. Thanks for the investigation on this! I learned a lot.

> Check otool -L lib/libdart-gui.6.6.0.dylib

I got this:
```
$ otool -L libdart-gui.6.5.0.dylib 
libdart-gui.6.5.0.dylib:
	/usr/local/opt/dartsim/lib/libdart-gui.6.5.dylib (compatibility version 6.5.0, current version 6.5.0)
	@rpath/libdart-utils.6.5.dylib (compatibility version 6.5.0, current version 6.5.0)
	/System/Library/Frameworks/GLUT.framework/Versions/A/GLUT (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libdart-external-lodepng.6.5.dylib (compatibility version 6.5.0, current version 6.5.0)
	@rpath/libdart-external-imgui.6.5.dylib (compatibility version 6.5.0, current version 6.5.0)
	@rpath/libdart.6.5.dylib (compatibility version 6.5.0, current version 6.5.0)
	/usr/local/opt/libccd/lib/libccd.2.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/local/opt/fcl/lib/libfcl.7.dylib (compatibility version 7.0.0, current version 0.5.0)
	/usr/local/opt/assimp/lib/libassimp.4.dylib (compatibility version 4.0.0, current version 4.1.0)
	/usr/local/opt/boost/lib/libboost_regex-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_filesystem-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libdart-external-odelcpsolver.6.5.dylib (compatibility version 6.5.0, current version 6.5.0)
	/usr/local/opt/tinyxml2/lib/libtinyxml2.6.dylib (compatibility version 6.0.0, current version 6.2.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```
Apparently, it links to the system GLUT.

**Comment by ilovezfs** [comment]
>Apparently, it links to the system GLUT.

And I assume you don't have X11 installed locally.

**Comment by ilovezfs** [comment]
>Thanks for the investigation on this! I learned a lot.

You're welcome!

**Pull request merged**
