### PR TITLE
Patch for double-delete issue reported by #671

### PR DESCRIPTION
**Pull request by mxgrey**

### CODE REVIEW

**Comment by jslee02** [comment]
:+1:

**Comment by scpeters** [comment]
:+1: I tested it against the failing gazebo test and it fixed it

**Comment by jslee02** [comment]
> I tested it against the failing gazebo test and it fixed it

Thanks. Once it's confirmed that this patch works, then I will upload the debian packages to [`ppa:dartsim`](https://launchpad.net/~dartsim/+archive/ubuntu/ppa/+packages).

**Comment by jslee02** [comment]
@scpeters The dart4 packages are uploaded to the [ppa:dartsim](https://launchpad.net/~dartsim/+archive/ubuntu/ppa/+packages) for trusty and wily. Also, [homebrew formula will be updated soon](https://github.com/dartsim/homebrew-dart/pull/16).

**Pull request merged**
