### PR TITLE
Add getters/setters for radii and diameters of EllipsoidShape

### PR DESCRIPTION
**Pull request by jslee02**
DART currently uses diameters for the primary properties of `EllipsoidShape`, which is not the commonly used convention. This PR is preliminary changes for replacing diameters with radii that include:
* deprecate get/setSize
* add get/setDiameter
* add get/setRadii

In the next major release, diameters will be totally replaced by radii.

---
This change is [Reviewable](https://reviewable.io/reviews/dartsim/dart/829)

### CODE REVIEW

**Comment by psigen** [comment]
Wait, I think we might have some confusion here.  I thought the conclusion in #827 was that semi-principal axis lengths (diameters) was the convention, but that the word `radii` was used to describe these lengths in certain places.

Am I missing something?

**Comment by jslee02** [comment]
Well, maybe I'm the one confused here. I understand that the lengths along the semi-principal axes (i.e., a, b, and c) represent the radii and that's the convention. Please correct me if I'm wrong.

**Comment by psigen** [comment]
Ok, I think the confusion stems from the following:
1. The lengths of the semi-principal axes are typically represented in *diameters* (distance from one side to the other, passing through the center of the ellipse.
2. The notation in DART describes ellipses in terms of _radii_, which usually means 1/2 of the diameter.

**Comment by ClintLiddick** [comment]
@psigen: @jslee02 and I talked, looked through wikipedia and the linked issue, and it seems like there was a miscommunication. Below is what we believe is correct.

1. Ellipsoids are most commonly parameterized by their semi-principal axes, which is equivalent to (but not called) the radii (i.e. they go from the center, through a focus, to an edge)
1. Principal axes are equivalent to diameter (from edge to edge, through center and foci)
1. Dart currently uses principle axes, but calls them diameter.
1. Dart wants to transition to using semi-principal axes, and in this PR (technically incorrectly) refers to it as this radii.

Dart *could* use either the principal or semi-principal axes, but should term them as such to avoid confusion.

**Comment by psigen** [comment]
Ah, this makes sense.  I think both JS and I had confusion around various terminology.

**Pull request merged**
