### PR TITLE
Fixing Inverse Kinematics for 6.0

### PR DESCRIPTION
**Pull request by mxgrey**
This PR fixes some issues with Inverse Kinematics which pertain to ``FreeJoint``, ``BallJoint``, and ``EndEffector``. It is targeted to be merged after #659.

There are two primary issues which were identified and fixed in this PR:

(1) Because ``FreeJoint`` and ``BallJoint`` positions cannot be integrated by simple addition, the Inverse Kinematics for these joints behaved incorrectly when they were not at zero. This PR fixes it by taking advantage of ``Joint::integratePositions(double)``. In the future, we might want a position integration which is agnostic to the current state. E.g:
```
Eigen::VectorXd Joint::integratePositions(const Eigen::VectorXd& positions, const Eigen::VectorXd& velocities) const
```

(2) When ``EndEffector``s and ``ShapeNode``s were being attached to their ``BodyNode``s, they were not recognized as being ``JacobianNode``s, because downcasting a pointer during construction is generally a bad idea. This PR fixes the issue, but now child ``BodyNode``s are identified as child ``JacobianNode``s via a separate pipeline than any other Node type, which is kind of smelly. In the future, we should probably unify the whole construction pipeline for ``BodyNode``s and all other ``Node`` types. BodyNodes might be kind of special, but I think we can still work out a better process than what we have right now.

I'm now going to attempt to patch these issues for ~~5.0 and~~ 5.1 without affecting their ABIs. Wish me luck.

---
This change is [Reviewable](https://reviewable.io/reviews/dartsim/dart/683)

### CODE REVIEW

**Comment by jslee02** [comment]
Reviewed 4 of 9 files at r1.
Review status: 4 of 9 files reviewed at latest revision, 11 unresolved discussions.

---

*[dart/dynamics/BodyNode.cpp, line 1443 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzHKGs7ihQajVZfLXS:-KFzHKGs7ihQajVZfLXT:-2036047242) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/dart/dynamics/BodyNode.cpp#L1443)):*
This has nothing to do with the main purpose of this PR, but it would be good to use `std::find` instead of just `find`.

---

*[dart/dynamics/BodyNode.cpp, line 1463 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzHZCBPgwBKWdm9b8E:-KFzHZCC3h2e5l_hVC2Z:1950240569) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/dart/dynamics/BodyNode.cpp#L1463)):*
ditto: `std::find`

---

*[dart/dynamics/BodyNode.cpp, line 1472 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzHlOkV-hdWj1wuahe:-KFzHlOkV-hdWj1wuahf:1950240569) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/dart/dynamics/BodyNode.cpp#L1472)):*
ditto: `std::find`

---

*[dart/dynamics/InverseKinematics.cpp, line 98 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzOkTBpkvkAHqecJ1s:-KFzOkTBpkvkAHqecJ1t:992471466) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/dart/dynamics/InverseKinematics.cpp#L98)):*
It seems this is a stop gap solution as we don't have a function of *position integration which is agnostic to the current state* you mentioned. Could we create an issue for this and leave a note here with the issue number?

---

*[dart/dynamics/InverseKinematics.cpp, line 100 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzHquVYjwh66XO2nzB:-KFzHquVYjwh66XO2nzC:-309988613) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/dart/dynamics/InverseKinematics.cpp#L100)):*
Since #681, we should use `std::size_t` rather than `size_t` for consistency. `auto i = 0u` would be an alternative if you like.

---

*[dart/dynamics/InverseKinematics.cpp, line 717 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzHu2ZFkwVDWC2y1FM:-KFzHu2ZFkwVDWC2y1FN:239206492) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/dart/dynamics/InverseKinematics.cpp#L717)):*
ditto: `std::size_t`

---

*[dart/dynamics/InverseKinematics.cpp, line 721 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzI90g3lSoywYi6fMX:-KFzI90g3lSoywYi6fMY:239206492) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/dart/dynamics/InverseKinematics.cpp#L721)):*
ditto: `std::size_t`

---

*[dart/dynamics/InverseKinematics.cpp, line 727 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzIA3NPvHcTTueDWzc:-KFzIA3NPvHcTTueDWzd:239206492) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/dart/dynamics/InverseKinematics.cpp#L727)):*
ditto: `std::size_t`

---

*[dart/dynamics/InverseKinematics.cpp, line 728 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzIAhTqQVTl93yAiqJ:-KFzIAhTqQVTl93yAiqK:239206492) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/dart/dynamics/InverseKinematics.cpp#L728)):*
ditto: `std::size_t`

---

*[dart/dynamics/InverseKinematics.cpp, line 1052 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzIE6_x-FOxeoUE00m:-KFzIE6_x-FOxeoUE00n:239206492) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/dart/dynamics/InverseKinematics.cpp#L1052)):*
ditto: `std::size_t`

---

*[dart/dynamics/InverseKinematics.h, line 511 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzNaANanUegzjmYoSQ:-KFzNaANanUegzjmYoSR:239206492) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/dart/dynamics/InverseKinematics.h#L511)):*
ditto: `std::size_t`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dartsim/dart/683)*

**Comment by jslee02** [comment]
Reviewed 4 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzXRCNhMH84l09BB6u:-KFzXRCNhMH84l09BB6v:-46795335) (no related file):*
This is not about the IK fix, but I've wondered if we can move out the nested classes in `InverseKinematics.h` outside of it for better readability. For example:
```cpp
class InverseKinematics : public common::Subject
{
  [...]

  class Function;

  [...]
};

class InverseKinematics::Function
{
  [...]
};
```

---

*[dart/constraint/BalanceConstraint.cpp, line 414 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzYtop37Nnf-QkmZmf:-KFzYtop37Nnf-QkmZmg:239206492) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/dart/constraint/BalanceConstraint.cpp#L414)):*
ditto: `std::size_t`

---

*[dart/constraint/BalanceConstraint.cpp, line 418 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzYwzNev1ox6zkVZm0:-KFzYwzNev1ox6zkVZm1:239206492) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/dart/constraint/BalanceConstraint.cpp#L418)):*
ditto: `std::size_t`

---

*[dart/dynamics/InverseKinematics.cpp, line 1042 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzYXeo5QVzNUtNIMqe:-KFzYXeo5QVzNUtNIMqf:239206492) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/dart/dynamics/InverseKinematics.cpp#L1042)):*
ditto: `std::size_t`

---

*[dart/dynamics/InverseKinematics.h, line 676 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzWWrWyF5ZZx4dFIJF:-KFzWWrWyF5ZZx4dFIJG:996323358) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/dart/dynamics/InverseKinematics.h#L676)):*
Could we rename this that doesn't have the suffix `_t` something like `ExtraDofUtilizationMethod` to follow the convention?

---

*[unittests/testForwardKinematics.cpp, line 222 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFz_VY23Uyf7-fKuW8H:-KFz_VY23Uyf7-fKuW8I:-566654708) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/unittests/testForwardKinematics.cpp#L222)):*
Maybe this test is not for #499.

---

*[unittests/testForwardKinematics.cpp, line 236 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFza_9IkX8z1Q986FgO:-KFza_9IkX8z1Q986FgP:239206492) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/unittests/testForwardKinematics.cpp#L236)):*
ditto: `std::size_t`

---

*[unittests/testForwardKinematics.cpp, line 237 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFzaXE4L97M7hm-Zj8q:-KFzaXE4L97M7hm-Zj8r:239206492) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/unittests/testForwardKinematics.cpp#L237)):*
ditto: `std::size_t`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dartsim/dart/683)*

**Comment by jslee02** [comment]
Reviewed 4 of 9 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dartsim/dart/683)*

**Comment by mxgrey** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[unittests/testForwardKinematics.cpp, line 222 \[r2\]](https://reviewable.io:443/reviews/dartsim/dart/683#-KFz_VY23Uyf7-fKuW8H:-KGDJqB720yBzbcxAOKm:118492612) ([raw file](https://github.com/dartsim/dart/blob/436c891ba81aeb664c1f1e63288de4beb9f487e9/unittests/testForwardKinematics.cpp#L222)):*
Woops, copy/paste error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dartsim/dart/683)*

**Comment by jslee02** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dartsim/dart/683#-:-KGDLdA0qgd7W5SVu4Xm:1417088721)*

**Pull request merged**
