### PR TITLE
Allow joint to recover after reaching position limits in servo mode

### PR DESCRIPTION
**Pull request by azeey**
Fixes https://github.com/dartsim/dart/issues/1683

***

#### Before creating a pull request

- ~[ ] Document new methods and classes~
- [x] Format new code files using ClangFormat by running `make format`
- [ ] Build with `-DDART_TREAT_WARNINGS_AS_ERRORS=ON` and resolve all the compile warnings

#### Before merging a pull request

- [ ] Set version target by selecting a milestone on the right side
- [ ] Summarize this change in `CHANGELOG.md`
- [ ] Add unit test(s) for this change
- [ ] Add Python bindings for new methods and classes

### CODE REVIEW

**Comment by jslee02** [comment]
For some reason, the CI is not being triggered for PRs from the forked repositories. Let's check the CI on the master branch after merging: https://github.com/dartsim/dart/actions

**Comment by azeey** [comment]
Is it because I had the target branch be `main` by mistake and then changed it to `release-6.13`?

**Comment by jslee02** [comment]
Ah, the CI wasn't configured to trigger CI on pull requests. It should be fixed now by c420a029c4abb95489364f8b10c12058f0cd3255, c63be9689d162c8368737402a7206c294ba8b238, 82bbe525fc8f8b245f8f48bc5bf6b3333ae857fe, 3e8133c79d67032ab35c05d8164f11a11d50f37b

**Comment by azeey** [comment]
@jslee02 would it be possible to get a new release of 6.13, maybe after https://github.com/dartsim/dart/pull/1779?

**Comment by jslee02** [comment]
Sounds good to me. Creating a tag for 6.13.[latest+1] would be enough?

**Comment by jslee02** [comment]
Done! https://github.com/dartsim/dart/releases/tag/v6.13.1

**Comment by azeey** [comment]
Thank you!!

**Pull request merged**
