### PR TITLE
Fixing handling of use_parent_model_frame tag in SdfParser (#893)

### PR DESCRIPTION
**Pull request by scpeters**
Backport #893 from master to release-6.2

### CODE REVIEW

**Comment by jslee02** [comment]
#893 was actually for 6.2.1 where currently release-6.2 branch is for it.

Sorry, I've been unclear that master branch was for which version. It used to be for 6.3 and now 6.2.1. To fix this, let me:
* merge master into release-6.2 so that all the patches for 6.2.1 that was merged to master to be applied to release-6.2
* bump up the version of master to 6.3.0. This could be 7.0 if necessary (by adding API breaking changes).

Once these are done, we might don't need this PR.

**Comment by scpeters** [comment]
ok, sorry I didn't know what was on the master branch. I was just trying to see when the changes from #893 will be released

**Comment by jslee02** [comment]
Closing this PR as #902 merged. I'm considering releasing 6.2.1 by this week.

**Comment by jslee02** [comment]
@scpeters FYI, DART 6.2.1 is released including the [debian packages](https://launchpad.net/~dartsim/+archive/ubuntu/ppa/+packages) and the [homebrew formulae](https://github.com/dartsim/homebrew-dart/pull/40).

**Pull request closed without merging**
