### PR TITLE
Remove overly cautious warning (#869)

### PR DESCRIPTION
**Pull request by yurket**
Remove overly cautious warning

***

**Before creating a pull request**

- [x] Document new methods and classes (N/A)
- [x] Format new code files using `clang-format` (N/A)

**Before merging a pull request**

- [x] Set version target by selecting a milestone on the right side (N/A)
- [x] Summarize this change in `CHANGELOG.md` (N/A)
- [x] Add unit test(s) for this change (N/A)

### CODE REVIEW

**Comment by yurket** [comment]
refers to #869

**Comment by mxgrey** [comment]
Thanks for this PR!

I think rather than just removing the warning, we should remove the entire limit check. As it is right now in this PR, the function will quit without allowing the rest position to be set outside the limits. However, there might be a legitimate use case where the rest position is outside of the limits, where the passive dynamics will clamp the joint down onto its joint limit.

For that reason, I would suggest removing all of lines 1470-1474.

**Comment by mxgrey** [comment]
Also with that change in behavior, I think it would be smart to set up a simple unit test.

The unit test could be as simple as a link attached to the world by a revolute joint where the revolute joint has some lower position limit, and its spring rest position is a lower value than its position limit (note that the spring stiffness should be something positive). Then the unit test can simulate the system for a second or two and check if the link comes to rest at its lower position limit.

**Comment by jslee02** [comment]
@mxgrey Your suggestions all sound good to me. I think we can merge this PR and address your suggestions as a separate PR.

**Comment by mxgrey** [comment]
To be honest I think this PR on its own is problematic because it removes a warning without removing behavior that is likely to surprise users. If we merge it in as-is, we risk the possibility that we forget to change this problematic behavior.

**Comment by yurket** [comment]
Agree with you, guys. Silent return doesn't look good. I'll add a test for the behavior.

**Comment by jslee02** [comment]
Thank you for your contribution. Closing in favor of #1418 that is a rework of this PR addressing @mxgrey's comments.

**Pull request closed without merging**
