### PR TITLE
DARTConfig relies on exported targets rather than find_library.

### PR DESCRIPTION
**Pull request by a-price**
Referencing the recommendations here:  [https://cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file](https://cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file) and here: [https://cmake.org/pipermail/cmake/2011-June/045050.html](https://cmake.org/pipermail/cmake/2011-June/045050.html), I changed the DARTConfig file to refer to the autogenerated targets in  DARTTargets.cmake, rather than searching for them with find_library.

This resolves issue #629 on my machine. An updated test project is attached.
[CMakeLists.txt](https://github.com/dartsim/dart/files/162348/CMakeLists.txt)
[test.txt](https://github.com/dartsim/dart/files/162349/test.txt)

### CODE REVIEW

**Comment by mkoval** [comment]
I have a two additional suggestions: 

1. Remove `"@CMAKE_INSTALL_PREFIX@/lib"` from `DART_LIBRARY_DIRS`; this is not necessary because we are using imported targets.
2. Set a `DART_${comp}_LIBRARY` variable for each component in `DART_FIND_COMPONENTS`, in addition to adding the library to `DART_LIBRARIES` (e.g. [see `FindBoost.cmake`](https://cmake.org/cmake/help/v3.0/module/FindBoost.html))

Neither of these are critical, but it would be nice to follow CMake conventions where possible.

**Comment by mxgrey** [comment]
Just to clarify for my own edification, when we call ``set(var target)``, does that give the full path of ``target`` to ``var``? What information is actually contained in a cmake target variable?

**Comment by a-price** [comment]
From my reading, the (autogenerated) `DARTTargets.cmake` file (and the file(s) it includes, like `DARTTargets-release.cmake`, define a set of CMake targets with certain properties. For instance, the Release version of target "dart" is configured with these lines on my machine:

> #Import target "dart" for configuration "Release"
> set_property(TARGET dart APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
> set_target_properties(dart PROPERTIES
>   IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "dart-core;/usr/lib/x86_64-linux-gnu/liburdfdom_sensor.so;/usr/lib/x86_64-linux-gnu/liburdfdom_model_state.so;/usr/lib/x86_64-linux-gnu/liburdfdom_model.so;/usr/lib/x86_64-linux-gnu/liburdfdom_world.so;/usr/lib/x86_64-linux-gnu/libconsole_bridge.so;/usr/lib/x86_64-linux-gnu/libtinyxml.so;/usr/lib/x86_64-linux-gnu/libtinyxml2.so"
>   IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libdart.so.5.1.1"
>   IMPORTED_SONAME_RELEASE "libdart.so.5.1"
>   )
> 
> list(APPEND _IMPORT_CHECK_TARGETS dart )
> list(APPEND _IMPORT_CHECK_FILES_FOR_dart "${_IMPORT_PREFIX}/lib/libdart.so.5.1.1" )
> 

So, CMake knows that there is a library called `dart`, that its location is `${_IMPORT_PREFIX}/lib/libdart.so.5.1.1`, and that it has certain link dependencies listed in `IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE`.

**Comment by mkoval** [comment]
Yes, @a-price's explanation is completely correct.

`DART_LIBRARIES` will contain the string `dart`. It's important to remember that this is the name of a **target, not a library**. The name of the `.so` file may not even be `dart.so` on disk, if you happened to use `set_target_properties` to change the target's `OUTPUT_NAME`.

**Comment by a-price** [comment]
Per suggestion, I added the `DART_<COMP>_LIBRARY` variable definition. I'm not sure I understand what the correct value of `DART_LIBRARY_DIRS` should be, though.

**Comment by mkoval** [comment]
I don't think we need to set `DART_LIBRARY_DIRS` at all. All of the necessary libraries, including transitive dependencies, are attached to the imported target.

**Comment by jslee02** [comment]
I agree with @mkoval . @a-price Could you remove `DART_LIBRARY_DIRS`? Thanks!

**Comment by jslee02** [comment]
:+1:

**Comment by mxgrey** [comment]
:+1:

**Comment by mkoval** [comment]
If there are no objections, can we merge this?

**Comment by jslee02** [comment]
Sure, merging.

**Pull request merged**
