### PR TITLE
Revision of #531

### PR DESCRIPTION
**Pull request by jslee02**
This pull request
* merges master branch into #531 (should pass appveyor tests)
* revises as discussed in #531

### CODE REVIEW

**Comment by jslee02** [comment]
A bug of VS2015 was reported pertain to `constexpr` with functions pointer ([see bug 1378031](http://blogs.msdn.com/b/vcblog/archive/2015/12/02/constexpr-in-vs2015-update-1.aspx)). The document says it's fixed, but [it seems not at least for our case](https://ci.appveyor.com/project/jslee02/dart/build/2397/job/6movxpwjt0cn3e30). Here is the error message:
```
[00:00:50] C:\projects\dart\dart/dynamics/Addon.h(63): error C2131: expression did not evaluate to a constant (compiling source file C:\projects\dart\dart\dynamics\BallJoint.cpp) [C:\projects\dart\build\dart\dart-core.vcxproj]
```

**Comment by mxgrey** [comment]
Is it possible that Appveyor doesn't have the latest updates for VS2015? Or have we found an extra-special case of the ``constexpr`` bug?

**Comment by jslee02** [comment]
The compilation errors are occurring with my VS2015, which is the most recent version with Update 1 (14.0.2478.2), as well. AppVeyor's one is 14.0.24720.0.

I can't say it's a VS2015 bug definitely, but it seems so for now.

**Comment by jslee02** [comment]
Merging even VS2015 can't build this.

**Pull request merged**
