### PR TITLE
Update changelog and contribution for #1620 and #1624

### PR DESCRIPTION
**Pull request by jslee02**
@azeey @costashatz Feel free to update the change log and the contribution descriptions. Thank you for your contributions again!

### CODE REVIEW

**Comment by costashatz** [comment]
@jslee02 fine for what you already have! Happy to contribute! Thanks for the awesome library!

**Comment by azeey** [comment]
> @jslee02 fine for me what you already have! Happy to contribute! Thanks for the awesome library!

Same here. Thanks for the reviews!

**Comment by costashatz** [comment]
@jslee02 I just saw that my PR id is wrong. The correct one is https://github.com/dartsim/dart/pull/1612.

**Comment by jslee02** [comment]
Oops, fixed in https://github.com/dartsim/dart/commit/021dd59f0971964495fad4e16073081d5e64dc62

**Pull request merged**
