### PR TITLE
Build and run tests on Windows CI

### PR DESCRIPTION
**Pull request by jslee02**

### CODE REVIEW

**Comment by scpeters** [comment]
I have some fixes for this in [branch scpeters:windows_linking_ode_tinyxml2](https://github.com/dartsim/dart/compare/master...scpeters:windows_linking_ode_tinyxml2)

it may also be helpful to look at the [diff without whitespace](https://github.com/dartsim/dart/compare/master...scpeters:windows_linking_ode_tinyxml2?w=1)

I can submit that as a PR against this branch if you prefer

**Comment by jslee02** [comment]
Awesome! Creating a PR against this branch works for me. Or you could directly push the changes to this branch/PR if preferred.

**Comment by traversaro** [comment]
I hope that the CI machine has enough size to contain all the tests: due to the use of the static linking, the test can weight up to 1 G
B each, so if there is some strange out of space error it could be due to that.

**Comment by jslee02** [comment]
> I have some fixes for this in [branch scpeters:windows_linking_ode_tinyxml2](https://github.com/dartsim/dart/compare/master...scpeters:windows_linking_ode_tinyxml2)
> 
> it may also be helpful to look at the [diff without whitespace](https://github.com/dartsim/dart/compare/master...scpeters:windows_linking_ode_tinyxml2?w=1)
> 
> I can submit that as a PR against this branch if you prefer

@scpeters Cherry-picked your commits. Thanks for the fixes!

> I hope that the CI machine has enough space to contain all the tests: due to the use of the static linking, the test can weight up to 1 GB each, so if there is some strange out of space error it could be due to that.

@traversaro Yeah, I noticed that too. For now, I disabled tests that fail on Windows to work around the issue. This PR is just to check if the linking issues are resolved, and the failing tests will be resolved in the next PRs.

**Comment by jslee02** [comment]
Merging this PR as the remained CI failures are unrelated to this PR. They will be resolved in the next PRs.

**Pull request merged**
