### PR TITLE
Build without ODE on Windows CI builds

### PR DESCRIPTION
**Pull request by jslee02**
To suppress build error: https://github.com/dartsim/dart/runs/621262581?check_suite_focus=true#step:3:1096

### CODE REVIEW

**Comment by traversaro** [comment]
FYI the vcpkg upstream error should be fixed (once merged) by https://github.com/microsoft/vcpkg/pull/11029 .

**Comment by jslee02** [comment]
@traversaro Wow, thanks! I should not merge this unless https://github.com/microsoft/vcpkg/pull/11029 is not merged in time. :smile:

**Comment by jslee02** [comment]
Well, on second thought, this should be merged for now because we use pre-installed vcpkg on GitHub Actions. :disappointed: Then revert once vcpkg is updated with your patch.

**Comment by traversaro** [comment]
You probably already know about this, but to avoid this kind of problems you could try the GitHub Action cache feature (https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows). It is quite convenient and it also have a flexible invalidation mechanism (so you can decide if the cache is invalidate if the vcpkg version changes or just when you explicitly invalidate it).

**Comment by jslee02** [comment]
It looks very promising! I know Travis and Appveyor support similar features but didn't know if GitHub Actions also supports it. Thanks!

**Pull request merged**
