### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by erwincoumans**
This fixes a crash on Windows. Confirmed to work in visual studio 2019.
See also https://github.com/dartsim/dart/issues/1431#issuecomment-622967308

[Remove this line and describe this pull request. Link to relevant GitHub issues, if any.]

***

**Before creating a pull request**

- [x] Document new methods and classes
- [x] Format new code files using `clang-format`

**Before merging a pull request**

- [ ] Set version target by selecting a milestone on the right side
- [ ] Summarize this change in `CHANGELOG.md`
- [ ] Add unit test(s) for this change

### CODE REVIEW

**Comment by traversaro** [comment]
I have some doubts related to the fact that just setting the flag `/vd2` could also change the ABI of classes with virtual bases that are not defined in DART, I tried a more localized approach in https://github.com/dartsim/dart/pull/1541 .

**Comment by erwincoumans** [comment]
good point, best to propagate the setting to users as well.

**Comment by erwincoumans** [comment]
Good point, best to propagate the setting to users as well. Do I need to close this request?

**Comment by erwincoumans** [comment]
Good point, that is even better. I'll close this request.

**Pull request closed without merging**
