### PR TITLE
Compute the IK error in the target reference frame rather than its parent

### PR DESCRIPTION
**Pull request by parkerowan**
This allows for relaxing different axis constraints in the target reference frame using existing error weights, e.g. ignoring rotation about the z vector of the target frame.

***

**Before creating a pull request**

- [ ] Document new methods and classes (modification to existing method)
- [x] Format new code files using `clang-format`

**Before merging a pull request**

- [ ] Set version target by selecting a milestone on the right side
- [ ] Summarize this change in `CHANGELOG.md`
- [ ] Add unit test(s) for this change

### CODE REVIEW

**Comment by mxgrey** [comment]
My memory from writing this is a bit hazy, so I'd need to think more about it to be certain, but if I remember correctly I think I implemented it like this to accurately represent the formal definition of a task space region. I think the difference in the frame of the target and the frame of the bounds is intentional because you may want to represent the desired end effector orientation independently of the bound coordinates.

A user could accomplish the effect of this PR by creating two `SimpleFrame` objects:

1. a `SimpleFrame` to represent the parent frame that defines the coordinates of the constraint bounds, and

2. a `SimpleFrame` which is a child of (1) to represent the target.

I think this PR would make us lose this flexibility.

That being said, I'd be open to optionally allowing users to explicitly specify a reference frame for the bounds of their Task Space Region. It could be added as a property to the `InverseKinematics::TaskSpaceRegion` class which defaults to a `nullptr`, and if it's a `nullptr` then the parent frame of the target will be used. This would have the bonus effect of preserving existing behavior.

**Comment by jslee02** [comment]
@mxgrey Thanks for the clarification. Reading the paper, I got why the parent of the target is used as the reference of bounds in the code; The parent of the target frame is the reference frame of TSR, denoted as `T_w`.

In addition to your suggestion (allowing to explicitly specifying the reference frame), I'd like to add a simpler error method that uses the target frame for the reference frame of bounds as well for the users who are not familiar with the TSR's frame conventions. Then the logic in this PR could be in that error method.

**Comment by mxgrey** [comment]
I have nothing against making it a separate error method, but one option to consider is to instead make a function that still returns a `TaskSpaceRegion` object which is configured to behave the way that's being discussed. That would reduce some duplicate implementation, since the behavior that's being proposed is just a subset of what a `TaskSpaceRegion` can do.

**Comment by jslee02** [comment]
> I have nothing against making it a separate error method, but one option to consider is to instead make a function that still returns a `TaskSpaceRegion` object, but have that object configured to behave the way that's being discussed. That would reduce some duplicate implementation, since the behavior that's being proposed is just a subset of what a `TaskSpaceRegion` can do.

All sounds good to me!

**Comment by parkerowan** [comment]
@mxgrey, @jslee02 Thanks for the feedback!

> That being said, I'd be open to optionally allowing users to explicitly specify a reference frame for the bounds of their Task Space Region. It could be added as a property to the InverseKinematics::TaskSpaceRegion class which defaults to a nullptr, and if it's a nullptr then the parent frame of the target will be used. This would have the bonus effect of preserving existing behavior.

This sounds like a good way to go for backward compatibility and flexibility.  I'll update the PR and add tests to capture both cases.

**Comment by jslee02** [comment]
Closing this PR in favor of https://github.com/dartsim/dart/pull/1548

**Pull request closed without merging**
