### PR TITLE
Packaging DART 5.0.1

### PR DESCRIPTION
**Pull request by jslee02**
DART 5.0.1 release includes patches for the bugs we found in DART 5.0.0. 

[DART 5.0.1 will be used in Gazebo 6.0](https://bitbucket.org/osrf/gazebo/pull-request/1825/dart-interface-update-for-dart-50/diff).

### CODE REVIEW

**Comment by mkoval** [comment]
Is it possible to get the `DartLoader` fixes from #439 into 5.0.1?

That pull request solely contains bugfixes, so it would be nice to get it into the patch.

**Comment by jslee02** [comment]
Yes, it's possible. In order to do that, we need another PR targeting `release-5.0` branch.

**Comment by mkoval** [comment]
@jslee02 I backported #439 to the `release-5.0` branch in #472.

**Comment by jslee02** [comment]
Thanks!

**Pull request merged**
