### PR TITLE
Add warnings for unsupported shape pairs of DARTCollisionDetector

### PR DESCRIPTION
**Pull request by jslee02**
This change is [Reviewable](https://reviewable.io/reviews/dartsim/dart/722)

### CODE REVIEW

**Comment by mxgrey** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[dart/collision/dart/DARTCollide.cpp, line 53 \[r1\]](https://reviewable.io:443/reviews/dartsim/dart/722#-KH_lnQoy-6q3xBr4jRE:-KH_lnQoy-6q3xBr4jRF:-1812831523) ([raw file](https://github.com/dartsim/dart/blob/0bbcfa4677a479ad6743f854c6d5ab2ad7723a04/dart/collision/dart/DARTCollide.cpp#L53)):*
> ```cpp
>         << getShapeName(shape1) << "'-'"\
>         << getShapeName(shape2) << "'. "\
>         << "Returning false.\n";
> ```

Maybe tweak this to:

```
  dterr << '[DARTCollisionDetector] Attempting to check for an "\
        << "unsupported shape pair: [" << typeid(*shape1).name()\
        << "] - [" << typeid(*shape2).name() << ]. Returning false.\n";
```

This way it would accurately report the issue even if a non-standard shape gets used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dartsim/dart/722)*

**Comment by jslee02** [comment]
*[dart/collision/dart/DARTCollide.cpp, line 53 \[r1\]](https://reviewable.io:443/reviews/dartsim/dart/722#-KH_lnQoy-6q3xBr4jRE:-KH_p73nki_agYM_ZwAC:-866479112) ([raw file](https://github.com/dartsim/dart/blob/0bbcfa4677a479ad6743f854c6d5ab2ad7723a04/dart/collision/dart/DARTCollide.cpp#L53)):*
<details><summary><i>Previously, mxgrey (Michael X. Grey) wrote…</i></summary>
> Maybe tweak this to:
> 
> ```
>   dterr << '[DARTCollisionDetector] Attempting to check for an "\
>         << "unsupported shape pair: [" << typeid(*shape1).name()\
>         << "] - [" << typeid(*shape2).name() << ]. Returning false.\n";
> ```
> 
> This way it would accurately report the issue even if a non-standard shape gets used.</details>
:+1: Good idea! I have a little concern that typeid(~).name() sometimes return a little bit mangled name, but I would prefer it since it's more flexible and the mangled​ name s are still reasonably readable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dartsim/dart/722)*

**Comment by mxgrey** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[dart/collision/dart/DARTCollide.cpp, line 53 \[r1\]](https://reviewable.io:443/reviews/dartsim/dart/722#-KH_lnQoy-6q3xBr4jRE:-KH_q4IsfHFz22Wzk-Lw:1120441099) ([raw file](https://github.com/dartsim/dart/blob/0bbcfa4677a479ad6743f854c6d5ab2ad7723a04/dart/collision/dart/DARTCollide.cpp#L53)):*
<details><summary><i>Previously, jslee02 (Jeongseok Lee) wrote…</i></summary>
> :+1: Good idea! I have a little concern that typeid(~).name() sometimes return a little bit mangled name, but I would prefer it since it's more flexible and the mangled​ name s are still reasonably readable.</details>
Yeah, it would be nice if a de-mangled "pretty print" version were available for typeid(~).name(), but we can always de-mangle the printout while debugging.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dartsim/dart/722)*

**Comment by mkoval** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[dart/collision/dart/DARTCollide.cpp, line 53 \[r1\]](https://reviewable.io:443/reviews/dartsim/dart/722#-KH_lnQoy-6q3xBr4jRE:-KHaHa_GV4J2PD22iikI:1176165657) ([raw file](https://github.com/dartsim/dart/blob/0bbcfa4677a479ad6743f854c6d5ab2ad7723a04/dart/collision/dart/DARTCollide.cpp#L53)):*
<details><summary><i>Previously, mxgrey (Michael X. Grey) wrote…</i></summary>
> Yeah, it would be nice if a de-mangled "pretty print" version were available for typeid(~).name(), but we can always de-mangle the printout while debugging.</details>
I would prefer to add virtual `getType` and a static getStaticType` functions, like we currently have on `Joint`. That way we get the best of both worlds: (1) no RTTI, which is brittle when using dynamic linking, (2) a readable name, and (3) user-extensibility. Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dartsim/dart/722)*

**Comment by jslee02** [comment]
*[dart/collision/dart/DARTCollide.cpp, line 53 \[r1\]](https://reviewable.io:443/reviews/dartsim/dart/722#-KH_lnQoy-6q3xBr4jRE:-KHb2wrMQXvwBF-yNG_n:1735911922) ([raw file](https://github.com/dartsim/dart/blob/0bbcfa4677a479ad6743f854c6d5ab2ad7723a04/dart/collision/dart/DARTCollide.cpp#L53)):*
<details><summary><i>Previously, mkoval (Michael Koval) wrote…</i></summary>
> I would prefer to add virtual `getType` and a static getStaticType` functions, like we currently have on `Joint`. That way we get the best of both worlds: (1) no RTTI, which is brittle when using dynamic linking, (2) a readable name, and (3) user-extensibility. Thoughts?</details>
My only concern is the performance of type checking. The cost would be virtual function call + string comparing. As I known, string comparing is just pointer comparison so virtual function call is the only overhead, right?

I don't have an objection to​ using type functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dartsim/dart/722)*

**Comment by jslee02** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[dart/collision/dart/DARTCollide.cpp, line 53 \[r1\]](https://reviewable.io:443/reviews/dartsim/dart/722#-KH_lnQoy-6q3xBr4jRE:-KHbu0K96otD4o1zZ_-R:-188028785) ([raw file](https://github.com/dartsim/dart/blob/0bbcfa4677a479ad6743f854c6d5ab2ad7723a04/dart/collision/dart/DARTCollide.cpp#L53)):*
<details><summary><i>Previously, jslee02 (Jeongseok Lee) wrote…</i></summary>
> My only concern is the performance of type checking. The cost would be virtual function call + string comparing. As I known, string comparing is just pointer comparison so virtual function call is the only overhead, right?
> 
> I don't have an objection to​ using type functions.</details>
I remember that there was one reason we stayed with enumerate​. The shape type wouldn't be easy to be extended with full support of related functionalities such as rendering and collision detection. Also, in general, `switch` statement with enumerate would be cheaper than `if-else if-else` statement. However, now I'm inclined to having `virtual getType()` because of consistency and that this is not the performance critical.

This can be handled in a separate PR. I'm merging this PR if there is no objection.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dartsim/dart/722)*

**Pull request merged**
